cardapio/urls.py
from django.conf.urls import url
from cardapio import views

urlpatterns = [
    url(r'^cardapios/$', views.listar, name="listar"),
    url(r'^cardapio/novo/$', views.cadastrar, name="cadastrar"),
    url(r'^cardapio/(?P<cardapio_id>\d+)/exibir/$', views.exibir, name="exibir"),
    url(r'^cardapio/(?P<cardapio_id>\d+)/editar/$', views.editar, name="editar"),
    url(r'^cardapio/(?P<cardapio_id>\d+)/deletar/$', views.deletar, name="deletar"),
]

cardapiocapaus/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from cardapio import urls as urls_cardapio
from usuarios import urls as urls_usuarios

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(urls_cardapio, namespace='cardapios')),
    url(r'^', include(urls_usuarios, namespace='usuarios')),
]

usuarios/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views

urlpatterns = [
    url(r'^usuario/login/$', login, {'template_name': 'login.html'}, name="login"),
    url(r'^usuario/cadastrar/$', views.cadastrar, name="cadastrar"),
    url(r'^usuario/logout/$', logout, name="logout"),
]

cardapio/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Cardapio(models.Model):
    '''Representa um cardapio'''
    data_cardapio = models.DateField('Data do prato')
    prato_principal = models.CharField('Prato Principal', max_length=200, null=False)
    sobremesa = models.CharField('Sobremesa',max_length=200)
    info_nutricionais = models.TextField('Informações Nutricionais')
    data_cadastro = models.DateTimeField('Data do cadastro', auto_now_add=True)
    data_update = models.DateTimeField('Data da ultima atualização', auto_now=True)
    usuario = models.ForeignKey(User, related_name="usuario")

    def __str__(self):
        return self.data_cardapio


    @property
    def get_usuario(self):
        return self.usuario.username

usuarios/models.py
from django.db import models

# Create your models here.

cardapio/forms.py
from django.forms import models
from .models import Cardapio

class FormularioCardapio(models.ModelForm):
    class Meta:
        model = Cardapio
        exclude = ['data_cadastro', 'usuario']

cardapio/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from cardapio.models import Cardapio
from cardapio.forms import FormularioCardapio
# Create your views here.
@login_required
def listar(request):
    query = request.GET.get('busca')
    if query:
       cardapios = Cardapio.objects.filter(prato_principal__icontains=query)
    else:
        cardapios = Cardapio.objects.all()
    return render(request, 'index.html', {'cardapios': cardapios})


@login_required
def cadastrar(request):
    form = FormularioCardapio(request.POST or None)
    if form.is_valid():
        cardapio = form.save(commit=False)
        cardapio.usuario = get_logado(request)
        cardapio.save()
        return redirect('cardapios:listar')
    return render(request, 'novo_cardapio.html', {'form': form})


@login_required
def exibir(request, cardapio_id):
    cardapio = Cardapio.objects.get(id=cardapio_id)
    return render(request, 'cardapio.html', {'cardapio': cardapio})


@login_required
def editar(request, cardapio_id):
    cardapio = Cardapio.objects.get(id=cardapio_id)
    if request.method == "POST":
        form = FormularioCardapio(request.POST, instance=cardapio)
        if form.is_valid():
            form.save()
            return redirect('cardapios:listar')
    else:
        form = FormularioCardapio(instance=cardapio)
    return render(request, 'editar_cardapio.html', {'form': form})


@login_required
def deletar(request, cardapio_id):
    cardapio = Cardapio.objects.get(id = cardapio_id)
    if request.method != "POST":
        cardapio.delete()
    return redirect('cardapios:listar')


@login_required
def get_logado(request):
   return request.user

usuarios/views.py
from django.shortcuts import render

# Create your views here.

def login(request):
    return render(request, 'login.html')


def cadastrar(request):
    pass

cardapio/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="pt">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width">
		<link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
		<link href="{% static "styles/main.css" %}" rel="stylesheet">
		<title>Cardapio IFPI - Campus Paulistana</title>
	</head>
	<body>
		<div class="container">
			<div class="header">
				<ul class="nav nav-pills pull-right">
					<li class=""><a href="#">{{user}}</a></li>
					<li class=""><a href="{% url 'usuarios:logout' %}">Logout</a></li>
				</ul>
				<h3 class="text-muted">Cardapio Capau</h3>
			</div>
			<div class="row content">
				{% block body %}
				{% endblock %}
			</div>
		</div>
	</body>
</html>

cardapio/templates/cardapio.html
{% extends "base.html" %}
{% block body %}
    <div clas="panel panel-default">
        <div class="panel-heading">
            <h1>
                {{ cardapio.data_cardapio }}
            </h1>
        </div>

        <div class="painel-body">
            <p><h3>Prato principal: {{ cardapio.prato_principal }}</h3></p>
            <p><h3>Sobremesa: {{ cardapio.sobremesa }}</h3></p>
            <p><h3>Informções nutricionais: {{ cardapio.info_nutricionais }}</h3></p>
            <p><h3>Cadastrado em: {{ cardapio.data_cadastro }}</h3></p>
            <p><h3>Por: {{ cardapio.get_usuario }}</h3></p>
        </div>
    </div>
    <hr>
    <div id="actions" class="row">
        <div class="col-md-12">
            <a href="{% url 'cardapios:listar' %}" class="btn btn-default">Voltar</a>
        </div>
    </div>

{% endblock %}

cardapio/templates/editar_cardapio.html
{% extends "base.html" %}
{% block body %}
    <h2>Novo Cardápio</h2>

    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <!-- area de campos do form -->
        <hr/>

        <div id="actions" class="row">
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary">Salvar</button>
                <a href="{% url 'cardapios:listar' %}" class="btn btn-default">Cancelar</a>
            </div>
        </div>
    </form>

{% endblock %}

cardapio/templates/index.html
{% extends "base.html" %}

{% block body %}
	<div class="col-lg-12">
		<div class="row">
			<div class="col-sm-6">
				<h2>Cardápios</h2>
			</div>



			<div class="col-sm-6 text-right h2">
				<a class="btn btn-primary" href="{% url 'cardapios:cadastrar' %}"><i class="fa fa-plus"></i>Novo + </a>
				<a class="btn btn-default" href="{% url 'cardapios:listar' %}"><i class="fa fa-refresh"></i> Atualizar</a>
			</div>
		</div>

        <form method="get">
            <input type="text" name="busca" placeholder="Buscar cardápio">
            <button type="submit" class="btn btn-primary">
                Buscar
            </button>
        </form>

		<hr>

		<table class="table table-hover">
			{% if cardapios %}
				<thead>
					<tr>
						<th>ID</th>
						<th>Data</th>
						<th width="35%">Prato Principal</th>
						<th>Opções</th>
					</tr>
				</thead>
				<tbody>
				{% for cardapio in cardapios %}
					<tr>
						<td>{{ cardapio.id }}</td>
						<td>{{ cardapio.data_cardapio }}</td>
						<td>{{ cardapio.prato_principal }}</td>
						<td class="actions text-right">
							<a href="{% url 'cardapios:exibir' cardapio.id %}" class="btn btn-sm btn-success"><i class="fa fa-eye"></i> Visualizar</a>
							<a href="{% url 'cardapios:editar' cardapio.id %}" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i> Editar</a>
							<a href="{% url 'cardapios:deletar' cardapio.id %}" class="btn btn-sm btn-danger" data-toggle="modal" data-target="#delete-modal"
                               data-customer="{{cardapio.id}}">
								<i class="fa fa-trash"></i> Excluir
							</a>
						</td>
					</tr>
				{% endfor %}
			{% else %}
				<tr>
					<td colspan="6">Nenhum registro encontrado.</td>
				</tr>
			{% endif %}
			</tbody>
		</table>

	</div>
{% endblock %}

cardapio/templates/novo_cardapio.html
{% extends "base.html" %}
{% block body %}
    <h2>Novo Cardápio</h2>

    <form method="post">
        {% csrf_token %}
        <!-- area de campos do form -->
        <hr/>
        <div class="row">
            <div class="form-group col-md-3">
                <label for="data_cardapio">Data</label>
                <input type="text" class="form-control" name="data_cardapio" id="data_cardapio">
            </div>

            <div class="form-group col-md-7">
                <label for="prato_principal">Prato Principal</label>
                <input type="text" class="form-control" required maxlength="200" name="prato_principal" id="prato_principal">
            </div>

            <div class="form-group col-md-5">
                <label for="sobremesa">Sobremesa</label>
                <input type="text" class="form-control" name="sobremesa" required maxlength="200" id="sombremesa">
            </div>
        </div>

        <div class="row">
            <div class="form-group col-md-12">
                <label for="info_nutricionais">Informações Nutricionais</label>
                <textarea name="info_nutricionais" cols="100" rows="10" required id="info_nutricionais"></textarea>
            </div>
        </div>
        <div id="actions" class="row">
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary">Salvar</button>
                <a href="{% url 'cardapios:listar' %}" class="btn btn-default">Cancelar</a>
            </div>
        </div>
    </form>

{% endblock %}

usuarios/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="pt">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width">
		<link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
		<link href="{% static "styles/main.css" %}" rel="stylesheet">
		<title>Cardapio IFPI - Campus Paulistana</title>
	</head>
	<body>
		<div class="container">
			<div class="header">
				<ul class="nav nav-pills pull-right">
					<li class=""><a href="#">{{user.nome}}</a></li>
					<li class=""><a href="{% url 'usuarios:logout' %}">Logout</a></li>
				</ul>
				<h3 class="text-muted">Cardapio Capau</h3>
			</div>
			<div class="row content">
				{% block body %}
				{% endblock %}
			</div>
		</div>
	</body>
</html>

usuarios/templates/login.html
{% extends "base.html" %}
{% block body %}
    <form class="form-signin" role="form" action="{% url 'usuarios:login' %}" method="post">
        {% csrf_token %}

        <h2 class="form-signin-heading">Login</h2>

        <input type="text" id="id_username" name="username" class="form-control" placeholder="Nome"
               required autofocus>

        <input type="password" id="id_password" name="password" class="form-control" placeholder="Senha"
               required>

        <button class="btn btn-lg btn-primary btn-block" type="submit" value="Login">Login</button>

        <input type="hidden" name="next" value="{{ next }}" />

        {% if form.errors %}
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            Por favor, verifique o Email e/ou Senha informados
          </div>
        {% endif %}

        <a href="#">registre-se</a>
    </form>
{% endblock %}